# Generated by Django 5.2.5 on 2025-08-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('nome_empresa', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='safevest.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarios', to='safevest.empresa')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='safevest.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Veste',
            fields=[
                ('id_veste', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='safevest.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsoVeste',
            fields=[
                ('id_uso', models.AutoField(primary_key=True, serialize=False)),
                ('inicio_uso', models.DateTimeField()),
                ('fim_uso', models.DateTimeField()),
                ('veste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='safevest.veste')),
            ],
        ),
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id_leitura', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('batimento', models.IntegerField()),
                ('temperatura_A', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_C', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_co', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_bateria', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_veste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='safevest.veste')),
            ],
        ),
    ]
