# Generated by Django 5.2.6 on 2025-11-11 19:15

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('nome_empresa', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('batimento', models.IntegerField(blank=True, null=True)),
                ('temperatura_A', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_C', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nivel_co', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nivel_bateria', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('deletado', models.BooleanField(default=False)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='safevest.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('Alerta', 'Alerta'), ('Emergência', 'Emergência')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('leitura_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safevest.leiturasensor')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='safevest.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='safevest.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='safevest.setor'),
        ),
        migrations.CreateModel(
            name='Veste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_de_serie', models.CharField(max_length=100, unique=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vestes', to='safevest.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UsoVeste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inicio_uso', models.DateTimeField()),
                ('fim_uso', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safevest.profile')),
                ('veste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safevest.veste')),
            ],
        ),
        migrations.AddField(
            model_name='leiturasensor',
            name='veste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='safevest.veste'),
        ),
    ]
