# Generated by Django 5.2.6 on 2025-11-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safevest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='setor',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
