# Generated by Django 5.2.6 on 2025-10-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safevest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='batimento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='nivel_bateria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='nivel_co',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='temperatura_A',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='temperatura_C',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
