# Generated by Django 5.2.6 on 2025-11-11 19:19

import safevest.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safevest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', safevest.models.UserManager()),
            ],
        ),
    ]
