# Generated by Django 5.1.1 on 2025-09-16 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safevest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('Alerta', 'Alerta'), ('Emergência', 'Emergência')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('leitura_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safevest.leiturasensor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='safevest.usuario')),
            ],
        ),
    ]
