# Generated by Django 5.2.6 on 2025-10-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safevest', '0002_profile_foto_perfil_alter_leiturasensor_batimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
