# Generated by Django 5.2.6 on 2025-09-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safevest', '0002_alerta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leiturasensor',
            old_name='id_veste',
            new_name='veste',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='veste',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='veste',
            old_name='id_veste',
            new_name='veste',
        ),
    ]
