# Generated by Django 5.2.6 on 2025-11-22 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safevest', '0002_remove_profile_setor_delete_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='veste',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vestes', to='safevest.empresa'),
        ),
        migrations.AddField(
            model_name='veste',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('inativo', 'Inativo')], default='ativa', max_length=20),
        ),
        migrations.AlterField(
            model_name='veste',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='veste',
            name='numero_de_serie',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
