# Generated by Django 5.2.6 on 2025-11-23 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safevest', '0003_veste_empresa_veste_status_alter_veste_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veste',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vestes', to='safevest.empresa'),
        ),
    ]
