# Generated by Django 5.2.6 on 2025-09-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safevest', '0003_rename_id_veste_leiturasensor_veste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veste',
            name='numero_de_serie',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='veste',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='safevest.usuario'),
        ),
    ]
